#  Print out any plugin errors to the console
console-logs: true

# Respawn players back to bingo spawn after a death
respawn-teleport: true

# Set this to true if you're using this on a SMP that has a dedicated bingo world
# Also be sure to set the name of your dedicated bingo world to ensure players
# aren't forced in to a new game or have their inventory cleared unless they are
# in the dedicated bingo world
multi-world-server: false

# This is only checked if the above setting is set to true. If you're using a plugin
# like multiverse, create a world dedicated for your bingo game and set the name here
bingo-world: default

# Should we add game results to the leaderboard where there is only 1 player in the game?
# This could be a way for players to inflate results so is disabled by default
count-solo-games: false

################################################
# Current game configuration - Don't manually change this
# Only adjust with the /bingo gui command in game
################################################

difficulty: easy
card-size: small
unique-card: false
full-card: false
game-mode: traditional
reveal-cards: true
game-time: 0
player-loadout: 0