name: Build project and create GitHub Release

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 16

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.2
      with:
        maven-version: 3.8.1

    - name: Build project
      run: mvn package -B

    - name: Get version from pom.xml
      id: version
      run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: List files in target directory
      run: ls -al ./target/

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/UltimateBingo-${{ env.VERSION }}.jar
        asset_name: UltimateBingo-${{ env.VERSION }}.jar
        asset_content_type: application/java-archive
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}